// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-g4fyh-XEQDASB08TRnV51mJp3WqRsEA',
    appId: '1:363338193447:web:c390cd7138020354d9cc02',
    messagingSenderId: '363338193447',
    projectId: 'zoom-7ce84',
    authDomain: 'zoom-7ce84.firebaseapp.com',
    storageBucket: 'zoom-7ce84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCgSnKf3R6vk2qg-XWtwsy_gi_UR5jvd4',
    appId: '1:363338193447:android:2fc888a58e51fcfed9cc02',
    messagingSenderId: '363338193447',
    projectId: 'zoom-7ce84',
    storageBucket: 'zoom-7ce84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM4wGWS6W5Hj60Qan7Y_9iSZ3qkddBe7c',
    appId: '1:363338193447:ios:32b66fe7d345fa98d9cc02',
    messagingSenderId: '363338193447',
    projectId: 'zoom-7ce84',
    storageBucket: 'zoom-7ce84.appspot.com',
    androidClientId: '363338193447-d8a5c6u9emb94nng98u6cl8ihrlpsga1.apps.googleusercontent.com',
    iosClientId: '363338193447-q3v1u7uvu67a6475sliaq4qrptp73958.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM4wGWS6W5Hj60Qan7Y_9iSZ3qkddBe7c',
    appId: '1:363338193447:ios:c87446f9dd80f3d0d9cc02',
    messagingSenderId: '363338193447',
    projectId: 'zoom-7ce84',
    storageBucket: 'zoom-7ce84.appspot.com',
    androidClientId: '363338193447-d8a5c6u9emb94nng98u6cl8ihrlpsga1.apps.googleusercontent.com',
    iosClientId: '363338193447-b549qeudtts3bv00ec160gdhpr56kgs8.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone.RunnerTests',
  );
}
